### ISSUE TITLE
hibernate-core-5.2.13-r3 fails with dev-java/javassist-3.29.0 from portage

### ISSUE THREAD

**Issue by efferre79** [6-6-6/spark-overlay#17] opened 2022-07-14 12:56 UTC
This is the error when trying to emerge:

```
 * Package:    dev-java/hibernate-core-5.2.13-r3
 * Repository: spark-overlay
 * Maintainer: zzy2529420793@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   compressdebug network-sandbox preserve-libs sandbox splitdebug userpriv usersandbox
 * Using: openjdk-8
>>> Unpacking source...
>>> Unpacking hibernate-core-5.2.13-bin.jar to /var/tmp/portage/dev-java/hibernate-core-5.2.13-r3/work/binjar
>>> Source unpacked in /var/tmp/portage/dev-java/hibernate-core-5.2.13-r3/work
>>> Preparing source in /var/tmp/portage/dev-java/hibernate-core-5.2.13-r3/work ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-java/hibernate-core-5.2.13-r3/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-java/hibernate-core-5.2.13-r3/work ...
 * java-pkg_ensure-dep: The ebuild is attempting to use hibernate-jpa-2.1-api, which is not declared with a SLOT i
n DEPEND.
javac -source 1.8 -target 1.8 -d target/classes -encoding UTF-8 -classpath /usr/share/hibernate-commons-annotations/lib/hibernate-commons-annotations.jar:/usr/share/hibernate-jpa-2.1-api/lib/hibernate-jpa.jar:/usr/share/jandex/lib/jandex.jar:/usr/share/jboss-transaction-api-1.2_spec/lib/jboss-transaction-api.jar:/usr/share/antlr/lib/antlr.jar:/usr/share/classmate/lib/classmate.jar:/usr/share/dom4j-1/lib/dom4j.jar:/usr/share/javassist-3/lib/javassist.jar:/usr/share/jboss-logging/lib/jboss-logging.jar:/usr/share/byte-buddy-1.6/lib/byte-buddy.jar:/usr/share/validation-api-2.0/lib/validation-api.jar:/usr/share/cdi-api-1.2/lib/cdi-api.jar:/usr/share/javax-security-jacc-api/lib/javax-security-jacc-api.jar:/usr/share/ant-core/lib/ant.jar:/usr/share/ant-core/lib/ant-bootstrap.jar:/usr/share/ant-core/lib/ant-launcher.jar:/usr/share/tomcat-servlet-api-4.0/lib/servlet-api.jar:/usr/share/tomcat-servlet-api-4.0/lib/el-api.jar:/usr/share/tomcat-servlet-api-4.0/lib/jsp-api.jar:/usr/share/jboss-logmanager/lib/jboss-logmanager.jar:/usr/share/log4j-12-api-2/lib/log4j-12-api.jar:/usr/share/log4j-api-2/lib/log4j-api.jar:/usr/share/slf4j-api/lib/slf4j-api.jar:/usr/share/jaxb-api-2/lib/jaxb-api.jar:/usr/share/xpp2/lib/PullParser.jar:/usr/share/xpp2/lib/PullParser-intf.jar:/usr/share/xpp2/lib/PullParser-standard.jar:/usr/share/xpp2/lib/PullParser-x2.jar:/usr/share/xpp3/lib/xpp3.jar:/usr/share/xsdlib/lib/xsdlib.jar:/usr/share/xerces-2/lib/xerces.jar:/usr/share/relaxng-datatype/lib/relaxng-datatype.jar:/usr/share/xml-commons-external-1.4/lib/xml-commons-external.jar:/usr/share/xml-commons-resolver/lib/xml-commons-resolver.jar:/usr/share/jboss-logging-annotations/lib/jboss-logging-annotations.jar:/usr/share/jakarta-interceptor-api-1/lib/jakarta-interceptor-api.jar:/usr/share/javax-inject/lib/javax-inject.jar:/usr/share/tomcat-servlet-api-3.0/lib/servlet-api.jar:/usr/share/tomcat-servlet-api-3.0/lib/el-api.jar:/usr/share/tomcat-servlet-api-3.0/lib/jsp-api.jar:/usr/share/jboss-modules/lib/jboss-modules.jar:/usr/share/log4j-core-2/lib/log4j-core.jar:/usr/share/jakarta-annotation-api/lib/jakarta-annotation-api.jar:/usr/share/jakarta-ejb-api-3/lib/jakarta-ejb-api.jar:/usr/share/jakarta-activation-api-1/lib/jakarta-activation-api.jar:/usr/share/commons-compress/lib/commons-compress.jar:/usr/share/commons-csv/lib/commons-csv.jar:/usr/share/conversant-disruptor/lib/conversant-disruptor.jar:/usr/share/jackson-core/lib/jackson-core.jar:/usr/share/jackson-databind/lib/jackson-databind.jar:/usr/share/jackson-dataformat-xml/lib/jackson-dataformat-xml.jar:/usr/share/jackson-dataformat-yaml/lib/jackson-dataformat-yaml.jar:/usr/share/jansi-2/lib/jansi.jar:/usr/share/javax-mail/lib/javax-mail.jar:/usr/share/jctools-core/lib/jctools-core.jar:/usr/share/jeromq/lib/jeromq.jar:/usr/share/kafka-clients/lib/kafka-clients.jar:/usr/share/lmax-disruptor/lib/lmax-disruptor.jar:/usr/share/woodstox-core/lib/woodstox-core.jar:/usr/share/glassfish-xmlrpc-api/lib/glassfish-xmlrpc-api.jar:/usr/share/jta/lib/jta.jar:/usr/share/jakarta-activation-1/lib/jakarta-activation.jar:/usr/share/asm-9/lib/asm.jar:/usr/share/asm-9/lib/asm-tree.jar:/usr/share/asm-9/lib/asm-analysis.jar:/usr/share/asm-9/lib/asm-commons.jar:/usr/share/asm-9/lib/asm-util.jar:/usr/share/brotli-dec/lib/brotli-dec.jar:/usr/share/xz-java/lib/xz-java.jar:/usr/share/zstd-jni/lib/zstd-jni.jar:/usr/share/jnacl/lib/jnacl.jar:/usr/share/lz4-java/lib/lz4-java.jar:/usr/share/snappy-1.1/lib/snappy.jar:/usr/share/osgi-core-api/lib/osgi-core-api.jar:/usr/share/msv/lib/msv.jar:/usr/share/stax2-api/lib/stax2-api.jar:/usr/share/jakarta-xml-soap-api-1/lib/jakarta-xml-soap-api.jar:/usr/share/iso-relax/lib/iso-relax.jar:/usr/share/jackson-annotations-2/lib/jackson-annotations.jar:/usr/share/snakeyaml/lib/snakeyaml.jar @sources.lst
src/main/java/org/hibernate/boot/archive/scan/spi/ClassFileArchiveEntryHandler.java:17: error: cannot access AnnotationsAttribute
import javassist.bytecode.AnnotationsAttribute;
                         ^
  bad class file: /usr/share/javassist-3/lib/javassist.jar(javassist/bytecode/AnnotationsAttribute.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

```

**Comment by efferre79** [comment] 2022-07-14 12:57
when using dev-java/javassist-3.21.0 from the overlay it works

**Comment by 6-6-6** [comment] 2022-09-28 07:25
i cannot reproduce the problem with
```
$ eix "hibernate-core|javassist"
[I] dev-java/hibernate-core [1]
     [redacted]
     Installed versions:  5.2.13-r3^t(03:22:40 PM 09/28/2022)(-binary -doc -source -test)
     [redacted]

[U] dev-java/javassist
    [redacted]
     Installed versions:  3.29.0-r2(3)^t(03:21:53 PM 09/28/2022)(-doc -source -test)
    [redacted]
```

maybe it has been fixed now : )

**Closed as completed by 6-6-6** 2022-09-28 07:25 UTC

**Comment by 6-6-6** [comment] 2022-09-28 08:06
seems related to
https://bugs.gentoo.org/857753
and
https://bugs.gentoo.org/857594
